--I
--1
ALTER TABLE HOCVIEN ADD GHICHU VARCHAR(50), DIEMTB NUMERIC(4,2), XEPLOAI VARCHAR(10)

--2

--3
ALTER TABLE HOCVIEN ADD CONSTRAINT CHECK_GTHV CHECK (GIOITINH IN ('Nam', 'Nu'))
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHECK_GTGV CHECK (GIOITINH IN ('Nam', 'Nu'))

--4 
ALTER TABLE KETQUATHI ADD CHECK 
(
	DIEM BETWEEN 0 AND 10
	AND RIGHT(DIEM , 3) LIKE '.__'
)

--5 
ALTER TABLE KETQUATHI ADD CHECK
(	
	(KQUA = 'Dat' AND DIEM BETWEEN 5 AND 10)
	OR (KQUA = 'Khong dat' AND DIEM < 5)
)

--6
ALTER TABLE KETQUATHI ADD CHECK (LANTHI <= 3)

--7 
ALTER TABLE GIANGDAY ADD CHECK (HOCKY BETWEEN 1 AND 3)

--8 
ALTER TABLE GIAOVIEN ADD CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))

--11 
ALTER TABLE HOCVIEN ADD CHECK (YEAR(GETDATE()) - YEAR(NGSINH) >= 18)

-- 12
ALTER TABLE GIANGDAY ADD CHECK (TUNGAY < DENNGAY)

--13
ALTER TABLE GIAOVIEN ADD CHECK (YEAR(NGVL) - YEAR(NGSINH) >= 22)

--14 
ALTER TABLE MONHOC ADD CONSTRAINT CHECK_TINCHI CHECK (ABS(TCLT - TCTH) <= 3)

--16 - 24
--II
--1
UPDATE GIAOVIEN
SET HESO = 0.2 + HESO
WHERE MAGV IN (SELECT TRGKHOA FROM KHOA)

--2 - 4

--III
--1
SELECT MAHV, (HO+' '+TEN), NGSINH, HOCVIEN.MALOP FROM HOCVIEN, LOP
WHERE HOCVIEN.MAHV = LOP.TRGLOP

--2 
SELECT  HOCVIEN.MAHV, (HO+' '+TEN), LANTHI, DIEM  FROM KETQUATHI, HOCVIEN
WHERE KETQUATHI.MAHV = HOCVIEN.MAHV
AND MAMH = 'CTRR'
AND MALOP = 'K12'
ORDER BY TEN, HO

--3 
SELECT HOCVIEN.MAHV, (HO+' '+TEN), TENMH FROM KETQUATHI, MONHOC, HOCVIEN
WHERE KETQUATHI.MAHV = HOCVIEN.MAHV
AND KETQUATHI.MAMH = MONHOC.MAMH
AND LANTHI = 1 AND KQUA = 'Dat'

--4 
SELECT HOCVIEN.MAHV, (HO+' '+TEN)
FROM HOCVIEN, KETQUATHI
WHERE HOCVIEN.MAHV = KETQUATHI.MAHV
AND MALOP = 'K11'
AND MAMH = 'CTRR'
AND KQUA = 'Khong Dat'
AND LANTHI = 1

--5 
SELECT DISTINCT HOCVIEN.MAHV, (HO+' '+TEN)
FROM HOCVIEN, KETQUATHI
WHERE HOCVIEN.MAHV = KETQUATHI.MAHV
AND MALOP like 'K%'
AND MAMH = 'CTRR'
AND EXISTS
(SELECT * FROM KetQuaThi 
WHERE KQua = 'Khong	Dat' 
AND MAMH = 'CTRR' 
AND MAHV = HOCVIEN.MAHV)

-- 6 
SELECT DISTINCT TENMH FROM MONHOC, GIAOVIEN, GIANGDAY
WHERE MONHOC.MAMH = GIANGDAY.MAMH
AND GIAOVIEN.MAGV = GIANGDAY.MAGV
AND HOTEN = 'Tran Tam Thanh'
AND HOCKY = 1 
AND NAM = 2006

--7 
SELECT DISTINCT MONHOC.MAMH, TENMH FROM MONHOC, LOP, GIANGDAY
WHERE GIANGDAY.MAMH = MONHOC.MAMH
AND GIANGDAY.MAGV = LOP.MAGVCN
AND LOP.MALOP = 'K11'
AND HOCKY = 1 
AND NAM = 2006

--8 
SELECT DISTINCT (HO+' '+TEN) FROM HOCVIEN, LOP, GIAOVIEN, GIANGDAY, MONHOC
WHERE LOP.TRGLOP = HOCVIEN.MAHV
AND GIANGDAY.MALOP = LOP.MALOP
AND GIANGDAY.MAGV = GIAOVIEN.MAGV
AND GIANGDAY.MAMH = MONHOC.MAMH
AND HOTEN = 'Nguyen To Lan'
AND TENMH = 'Co So Du Lieu'

-- 9
SELECT MONHOCTRUOC.MAMH, MONHOCTRUOC.TENMH FROM MONHOC, MONHOC AS MONHOCTRUOC, DIEUKIEN
WHERE MONHOC.MAMH = DIEUKIEN.MAMH
AND MONHOCTRUOC.MAMH = DIEUKIEN.MAMH_TRUOC
AND MONHOC.TENMH = 'Co So Du Lieu'

--10
SELECT MONHOC.MAMH, MONHOC.TENMH FROM MONHOC, MONHOC AS MONHOCTRUOC, DIEUKIEN
WHERE MONHOC.MAMH = DIEUKIEN.MAMH
AND MONHOCTRUOC.MAMH = DIEUKIEN.MAMH_TRUOC
AND MONHOCTRUOC.TENMH = 'Cau Truc Roi Rac'

--11
SELECT GIAOVIEN.HOTEN FROM GIAOVIEN, GIANGDAY
WHERE GIAOVIEN.MAGV = GIANGDAY.MAGV
AND MALOP = 'K11' AND MALOP = 'K12'
AND HOCKY = 1
AND NAM = 2006

--12
SELECT HOCVIEN.MAHV, (HO+' '+TEN) FROM HOCVIEN, KETQUATHI
WHERE HOCVIEN.MAHV = KETQUATHI.MAHV
AND MAMH = 'CSDL' 
AND LANTHI = 1 
AND KQUA = 'Khong Dat'
AND NOT EXISTS 
(SELECT * FROM KETQUATHI WHERE LANTHI > 1 AND KETQUATHI.MAHV = HOCVIEN.MAHV)

--13
SELECT MAGV, HOTEN FROM GIAOVIEN
WHERE MAGV 
NOT IN (SELECT MAGV FROM GIANGDAY)

--14

--15

--16
SELECT HOTEN FROM GIAOVIEN, GIANGDAY
WHERE GIAOVIEN.MAGV = GIANGDAY.MAGV
AND MAMH = 'CTRR'
GROUP BY GIAOVIEN.MAGV, HOTEN, HOCKY
HAVING COUNT(*) >= 2

--17
SELECT HOCVIEN.*, DIEM AS 'Điểm thi CSDL sau cùng' FROM HOCVIEN, KETQUATHI
WHERE HOCVIEN.MAHV = KETQUATHI.MAHV
AND MAMH = 'CSDL'
AND LANTHI = 
(
	SELECT MAX(LANTHI) 
	FROM KETQUATHI
	WHERE MAMH = 'CSDL' AND KETQUATHI.MAHV = HOCVIEN.MAHV
	GROUP BY MAHV
)

--18
SELECT HOCVIEN.*, DIEM FROM	HOCVIEN, KETQUATHI, MONHOC
WHERE HOCVIEN.MAHV = KETQUATHI.MAHV
AND KETQUATHI.MAMH = MONHOC.MAMH
AND TENMH = 'Co So Du Lieu'
AND DIEM = 
(
	SELECT MAX(DIEM) FROM KETQUATHI, MONHOC
	WHERE KETQUATHI.MAMH = MONHOC.MAMH
	AND MAHV = HOCVIEN.MAHV
	AND TENMH = 'Co So Du Lieu'
	GROUP BY MAHV
)

--19
SELECT MAKHOA, TENKHOA FROM KHOA
WHERE NGTLAP = (SELECT MIN(NGTLAP) FROM KHOA)

--20
SELECT COUNT(*) FROM GIAOVIEN
WHERE HOCHAM IN ('GS', 'PGS')

--21
SELECT MAKHOA, HOCVI, COUNT(*) FROM GIAOVIEN
GROUP BY MAKHOA, HOCVI
ORDER BY MAKHOA

--22
SELECT MAMH, KQUA, COUNT(*) FROM KETQUATHI
GROUP BY MAMH, KQUA
ORDER BY MAMH

--23
SELECT DISTINCT GIAOVIEN.MAGV, HOTEN FROM GIAOVIEN, LOP, GIANGDAY
WHERE GIANGDAY.MALOP = LOP.MALOP
AND GIANGDAY.MAGV = GIAOVIEN.MAGV
AND GIAOVIEN.MAGV = LOP.MAGVCN

--24
SELECT HO+' '+TEN FROM HOCVIEN, LOP
WHERE HOCVIEN.MAHV = LOP.TRGLOP
AND LOP.SISO = (SELECT MAX(SISO) FROM LOP)

--25
SELECT HO + ' ' + TEN FROM HOCVIEN, LOP, KETQUATHI
WHERE HOCVIEN.MAHV = LOP.TRGLOP
AND HOCVIEN.MAHV = KETQUATHI.MAHV
AND KQUA = 'Khong Dat'
GROUP BY TRGLOP, HO, TEN
HAVING COUNT(*) > 3

--26
SELECT TOP 1 HOCVIEN.MAHV, (HO+' '+TEN) AS HOTEN FROM HOCVIEN, KETQUATHI
WHERE HOCVIEN.MAHV = KETQUATHI.MAHV
AND DIEM >= 9
GROUP BY HOCVIEN.MAHV, HO, TEN
ORDER BY COUNT(*) DESC

--27

--28
SELECT MAGV, COUNT(DISTINCT MAMH), COUNT(DISTINCT MALOP) FROM GIANGDAY
GROUP BY MAGV

--29
